### ISSUE TITLE
请问Tenda AC21的固件是怎么解开的呢?我用binwalk解不开,谢谢

### ISSUE THREAD

**Issue by MaryDBurke01** [xxy1126/Vuln#1]

**Comment by xxy1126** [comment]
你好,  这个固件是从真实设备里用tftp传出来的, 关于这个固件解包, 我也在研究

**Comment by MaryDBurke01** [comment]
> 你好, 这个固件是从真实设备里用tftp传出来的, 关于这个固件解包, 我也在研究

我以为是直接binwalk解密出来的呢,哈哈,这个解密有研究是在uboot里还是在httpd里吗?

**Comment by xxy1126** [comment]
> > 你好, 这个固件是从真实设备里用tftp传出来的, 关于这个固件解包, 我也在研究
> 
> 我以为是直接binwalk解密出来的呢,哈哈,这个解密有研究是在uboot里还是在httpd里吗?

我感觉应该不是加密, 就应该单纯binwalk 没识别出来

**Comment by badmonkey7** [comment]
> 你好, 这个固件是从真实设备里用tftp传出来的, 关于这个固件解包, 我也在研究

但是设备的uart没有shell啊，这个tftp是用uboot的tftp嘛？没有具体的文档不太知道怎么用RealTek的tftp，您能讲讲具体是怎么tftp出来的嘛？

**Comment by xxy1126** [comment]
> RealTek

uart不行的话, 这个设备有个后门可以开启telnet, 访问链接http://xxxxxxx/goform/telnet. 然后可以用python构建一个tftp服务器或者是下载一个tftp软件

**Comment by xxy1126** [comment]
> 但是设备的uart没有shell啊，这个tftp是用uboot的tftp嘛？没有具体的文档不太知道怎么用RealTek的tftp，您能讲讲具体是怎么tftp出来的嘛？

uart不行的话, 这个设备有个后门可以开启telnet, 访问链接http://xxxxxxx/goform/telnet. 然后可以用python构建一个tftp服务器或者是下载一个tftp软件

**Comment by badmonkey7** [comment]
> 

好的，好的。谢谢了用户密码在这里https://www.secpulse.com/archives/180622.html
